# Generated by Django 2.2.6 on 2019-10-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Album Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Album Description')),
                ('path', models.CharField(max_length=200, verbose_name='Album Path')),
                ('cover', models.CharField(max_length=120, verbose_name='Album Cover Name')),
            ],
        ),
    ]
